# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if 
# you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Unit Test Workflow

# This describes when the workflow is executed.
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

  # workflow_dispatch allows manual execution of the workflow.
  workflow_dispatch:

jobs:

  # This is the name of the job.
  build:

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Build Tools
      run: |
        sudo apt update 
        sudo apt install ninja-build

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake --preset unit-tests

    - name: Build
      # Build your program with the given configuration
      run: cmake --build --preset unit-tests 

    - name: Test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --preset unit-tests

